export const SET_WORKFLOW_DETAILS = "SET_WORKFLOW_DETAILS";
export const ADD_ELEMENTS = "ADD_ELEMENTS";
export const CONTACTS_SELECTED = "CONTACTS_SELECTED";
export const REMOVE_END_ELEMENTS = "REMOVE_END_ELEMENTS";
export const ADD_STEP_ELEMENT = "ADD_STEP_ELEMENT";
export const SMS_DETAILS = "SMS_DETAILS";
export const SET_DELAY = "SET_DELAY";
export const SET_CONDITION = "SET_CONDITION";
